### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by luciantunez** [Danielmoraisg/Count_cells#2]
Hello and thank you for sharing your work!
Could you please provide the last checkpoint for the pretrained model?
Thank you in advance, Lucia

**Comment by Danielmoraisg** [comment]
Hi lucia

The pre trained model used by the fastai v1 package is the resnet50 from [torchvision.models](https://pytorch.org/vision/stable/models.html#) If you download and install pytorch you should be able to get access to the pretrained resnet50. You can find more information about this model [here](https://arxiv.org/pdf/1512.03385.pdf)

Hope it helps, Daniel

**Comment by luantunez** [comment]
Thank you for your quick response!
I am however refering to your last checkpoint with your transfer learning applied.
Would it be possible for you to share that please?
Thank you! Lucia

**Comment by Danielmoraisg** [comment]
I see, unfortunately I don't have it anymore, but you can run the script in google colab and it should give you similar results
Sorry for not being able to help,
Daniel
